### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lilcsz** [R3v0lty/InstaReader#1]
C:\Users\MNT\Desktop\2\>php reader.php
PHP Warning:  file_get_contents(contacts.json): failed to open stream: No such file or directory in C:\Users\MNT\Desktop\2\reader.php on line 19

Warning: file_get_contents(contacts.json): failed to open stream: No such file or directory in C:\Users\MNT\Desktop\Dosyalar\crack stuff\IN\reader.php on line 19
PHP Warning:  Invalid argument supplied for foreach() in C:\Users\MNT\Desktop\2\reader.php on line 21

Warning: Invalid argument supplied for foreach() in C:\Users\MNT\Desktop\Dosyalar\crack stuff\IN\reader.php on line 21

**Comment by R3v0lty** [comment]
u need to place the script within the directory of extracted backup file where there should be a file named "contacts.json", if it is not there just create an empty file with that name. it is easy to add arguments to target specific task but since it's meant to be used on the fly so i'm leaving it as is.
